default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: <%= ENV.fetch('DATABASE_URL') { 'wifirst_interview_development' } %>

test:
  <<: *default
  database: <%= ENV.fetch('DATABASE_URL') { 'wifirst_interview_test' } %>

production:
  <<: *default
  timeout: 5000
  pool: 15
  database: <%= ENV['DATABASE_URL'] %>
